//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_base : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean click
        {
            get
            {
                return SteamVR_Actions.base_click;
            }
        }
        
        public virtual SteamVR_Action_Boolean double_click
        {
            get
            {
                return SteamVR_Actions.base_double_click;
            }
        }
        
        public virtual SteamVR_Action_Vibration NewAction
        {
            get
            {
                return SteamVR_Actions.base_NewAction;
            }
        }
    }
}
